#!/usr/bin/env python3
"""Flash ESP32 firmware through esptool.py with auto-detection.

Supports ESP-IDF, Arduino-ESP32, and PlatformIO projects.
Auto-detects serial port, chip model, and built .bin files with partition offsets.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from detect_esp_device import detect_devices, find_esptool, Device


@dataclass
class FlashImage:
    """A binary image to flash at a specific offset."""
    offset: str  # hex string like "0x10000"
    path: Path
    role: str  # bootloader / partition-table / app / ota_data / nvs / custom


@dataclass
class FlashResult:
    success: bool
    port: str = ""
    chip: str = ""
    images: list[FlashImage] = field(default_factory=list)
    command: str = ""
    output: str = ""
    error: str = ""


def run_command(command: list[str], timeout: int = 120, capture: bool = True) -> tuple[int, str, str]:
    """Run a command, return (returncode, stdout, stderr)."""
    try:
        if capture:
            completed = subprocess.run(
                command,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=timeout,
            )
            return completed.returncode, completed.stdout, completed.stderr
        else:
            # Stream output to console
            completed = subprocess.run(command, timeout=timeout)
            return completed.returncode, "", ""
    except subprocess.TimeoutExpired as exc:
        return -1, "", f"Command timed out after {exc.timeout}s"
    except FileNotFoundError as exc:
        return -1, "", f"Command not found: {exc}"


def detect_project_type(root: Path) -> str:
    """Detect project type: esp-idf / arduino / platformio / unknown."""
    cmakelists = root / "CMakeLists.txt"
    platformio_ini = root / "platformio.ini"
    ino_files = list(root.rglob("*.ino"))

    if cmakelists.exists():
        content = cmakelists.read_text(encoding="utf-8", errors="replace")
        if "IDF_PATH" in content or "project.cmake" in content:
            return "esp-idf"
    if platformio_ini.exists():
        return "platformio"
    if ino_files:
        return "arduino"
    return "unknown"


def find_esp_idf_binaries(root: Path) -> list[FlashImage]:
    """Find bootloader, partition-table, and app binaries in an ESP-IDF build directory."""
    build_dir = root / "build"
    if not build_dir.exists():
        return []

    images = []
    project_name = root.name

    # Bootloader: offset 0x0 (ESP32 classic) or 0x0 (all chips in IDF v5)
    bootloader = build_dir / "bootloader" / "bootloader.bin"
    if bootloader.exists():
        images.append(FlashImage(offset="0x0", path=bootloader, role="bootloader"))

    # Partition table: offset 0x8000
    part_table = build_dir / "partition_table" / "partition-table.bin"
    if part_table.exists():
        images.append(FlashImage(offset="0x8000", path=part_table, role="partition-table"))

    # OTA data initial: offset 0xe000 (if OTA partition table)
    ota_data = build_dir / "ota_data_initial.bin"
    if ota_data.exists():
        images.append(FlashImage(offset="0xe000", path=ota_data, role="ota_data"))

    # App binary: offset 0x10000 (default for single app)
    # Try project name first, then any .bin in build root
    app_bin = build_dir / f"{project_name}.bin"
    if not app_bin.exists():
        # Search for the largest .bin in build root (usually the app)
        candidates = [f for f in build_dir.glob("*.bin") if f.name not in ("bootloader.bin",)]
        if candidates:
            app_bin = max(candidates, key=lambda f: f.stat().st_size)

    if app_bin.exists():
        # Determine app offset from partition table if possible
        app_offset = "0x10000"  # default
        # Check flash_args file generated by IDF
        flash_args = build_dir / "flash_args"
        if flash_args.exists():
            content = flash_args.read_text(encoding="utf-8", errors="replace")
            # Parse: write_flash --flash_mode dio ... 0x0 bootloader.bin 0x8000 partition-table.bin 0x10000 app.bin
            parts = content.split()
            for i, part in enumerate(parts):
                if re.match(r"^0x[0-9a-fA-F]+$", part):
                    # This is an offset; next part should be a file path
                    if i + 1 < len(parts):
                        fname = os.path.basename(parts[i + 1])
                        if fname == app_bin.name:
                            app_offset = part
                            break

        images.append(FlashImage(offset=app_offset, path=app_bin, role="app"))

    return images


def find_platformio_binaries(root: Path) -> list[FlashImage]:
    """Find firmware binary in a PlatformIO build directory."""
    images = []
    # PlatformIO default output: .pio/build/<env>/firmware.bin
    pio_build = root / ".pio" / "build"
    if pio_build.exists():
        for env_dir in pio_build.iterdir():
            if env_dir.is_dir():
                firmware = env_dir / "firmware.bin"
                if firmware.exists():
                    images.append(FlashImage(offset="0x10000", path=firmware, role="app"))
                    # PlatformIO also generates bootloader and partitions in some cases
                    bootloader = env_dir / "bootloader.bin"
                    if bootloader.exists():
                        images.append(FlashImage(offset="0x0", path=bootloader, role="bootloader"))
                    partitions = env_dir / "partitions.bin"
                    if partitions.exists():
                        images.append(FlashImage(offset="0x8000", path=partitions, role="partition-table"))
                    break
    return images


def find_arduino_binaries(root: Path) -> list[FlashImage]:
    """Find compiled binary in an Arduino project build directory."""
    images = []
    # arduino-cli output is usually in a temp directory; user should specify --bin
    # Check common locations
    build_dir = root / "build"
    if build_dir.exists():
        for f in build_dir.rglob("*.bin"):
            if "bootloader" not in f.name.lower():
                images.append(FlashImage(offset="0x10000", path=f, role="app"))
                break
    return images


def find_binaries(root: Path, project_type: str) -> list[FlashImage]:
    """Find flashable binaries based on project type."""
    if project_type == "esp-idf":
        return find_esp_idf_binaries(root)
    elif project_type == "platformio":
        return find_platformio_binaries(root)
    elif project_type == "arduino":
        return find_arduino_binaries(root)
    return []


def select_port(devices: list[Device], preferred: str = "") -> Optional[Device]:
    """Select the best port from detected devices."""
    if preferred:
        for d in devices:
            if d.port.upper() == preferred.upper():
                return d
        # If preferred port not in detected list, create a generic device
        return Device(port=preferred, kind="manual", display_name=f"Manual port {preferred}", confidence="medium")

    # Prefer high-confidence devices (identified chip)
    high_conf = [d for d in devices if d.confidence == "high" and d.port]
    if high_conf:
        return high_conf[0]

    # Then medium confidence known USB-UART
    medium = [d for d in devices if d.confidence == "medium" and d.port and d.kind != "generic-serial"]
    if medium:
        return medium[0]

    # Then any device with a port
    with_port = [d for d in devices if d.port]
    if with_port:
        return with_port[0]

    return None


def build_flash_command(esptool: str, chip: str, port: str, baud: int,
                        images: list[FlashImage], flash_mode: str = "dio",
                        flash_freq: str = "80m", flash_size: str = "detect",
                        verify: bool = True, erase: bool = False) -> list[str]:
    """Build the esptool write_flash command."""
    cmd = esptool.split()
    cmd.extend(["--chip", chip, "--port", port, "--baud", str(baud)])
    cmd.extend(["--before", "default_reset", "--after", "hard_reset"])

    if erase:
        cmd.append("erase_flash")
        return cmd

    cmd.append("write_flash")
    cmd.extend(["--flash_mode", flash_mode])
    cmd.extend(["--flash_freq", flash_freq])
    cmd.extend(["--flash_size", flash_size])
    if verify:
        cmd.append("--verify")

    for img in images:
        cmd.extend([img.offset, str(img.path)])

    return cmd


def flash_project(root: Path, port: str = "", baud: int = 460800, chip: str = "",
                  erase: bool = False, verify: bool = True, dry_run: bool = False,
                  no_identify: bool = False) -> FlashResult:
    """Flash an ESP32 project.

    Args:
        root: Project directory
        port: Serial port (auto-detected if empty)
        baud: Baud rate
        chip: Chip model (auto-detected if empty)
        erase: Erase entire flash before flashing
        verify: Verify after writing
        dry_run: Print command without executing
        no_identify: Skip esptool chip_id identification

    Returns:
        FlashResult with success status and details
    """
    result = FlashResult(success=False)
    root = root.resolve()

    # 1. Detect project type
    project_type = detect_project_type(root)
    if project_type == "unknown":
        result.error = f"Unrecognized project type in {root}. Expected ESP-IDF, Arduino, or PlatformIO."
        return result

    # 2. Find esptool
    esptool = find_esptool()
    if not esptool:
        result.error = "esptool.py not found. Install ESP-IDF or run: pip install esptool"
        return result

    # 3. Detect devices
    devices = detect_devices(identify=not no_identify)

    # 4. Select port
    device = select_port(devices, port)
    if not device:
        result.error = ("No serial port found and none specified. "
                        "Connect your ESP32 board and ensure drivers are installed. "
                        "Use --port COMx to specify manually.")
        return result
    result.port = device.port

    # 5. Determine chip
    if chip:
        result.chip = chip
    elif device.chip_model:
        result.chip = device.chip_model
    else:
        # Try to read from sdkconfig
        sdkconfig = root / "sdkconfig"
        if sdkconfig.exists():
            content = sdkconfig.read_text(encoding="utf-8", errors="replace")
            m = re.search(r'^CONFIG_IDF_TARGET="(\w+)"', content, re.MULTILINE)
            if m:
                result.chip = m.group(1)

    if not result.chip:
        result.error = ("Could not determine chip model. Specify with --chip esp32s3 (or esp32, esp32c3, etc.). "
                        "Or run esptool chip_id to identify the connected board.")
        return result

    # 6. Find binaries
    images = find_binaries(root, project_type)

    # If explicit --bin was provided, it would be handled by caller; here we auto-find
    if not images and not erase:
        result.error = (f"No build outputs found in {root}. Run 'idf.py build' (ESP-IDF), "
                        f"'pio run' (PlatformIO), or 'arduino-cli compile' (Arduino) first.")
        return result

    result.images = images

    # 7. Determine flash settings from sdkconfig
    flash_mode = "dio"
    flash_freq = "80m"
    flash_size = "detect"
    sdkconfig = root / "sdkconfig"
    if sdkconfig.exists():
        content = sdkconfig.read_text(encoding="utf-8", errors="replace")
        m = re.search(r'^CONFIG_ESPTOOLPY_FLASHMODE_(\w+)=y', content, re.MULTILINE)
        if m:
            flash_mode = m.group(1).lower()
        m = re.search(r'^CONFIG_ESPTOOLPY_FLASHFREQ_(\w+)=y', content, re.MULTILINE)
        if m:
            freq = m.group(1).lower()
            # Convert "80M" to "80m"
            flash_freq = freq.replace("m", "m")
        m = re.search(r'^CONFIG_ESPTOOLPY_FLASHSIZE_(\w+)=y', content, re.MULTILINE)
        if m:
            flash_size = m.group(1).upper().replace("MB", "MB")
            # esptool expects "detect" or "4MB" etc.
            if flash_size.endswith("MB"):
                flash_size = flash_size  # already correct format

    # 8. Build command
    cmd = build_flash_command(
        esptool=esptool,
        chip=result.chip,
        port=result.port,
        baud=baud,
        images=images,
        flash_mode=flash_mode,
        flash_freq=flash_freq,
        flash_size=flash_size,
        verify=verify,
        erase=erase,
    )
    result.command = " ".join(cmd)

    if dry_run:
        result.success = True
        result.output = "[DRY RUN] Command not executed."
        return result

    # 9. Execute
    print(f"Flashing {result.chip} on {result.port} at {baud} baud...")
    print(f"Command: {result.command}")
    print("-" * 70)

    returncode, stdout, stderr = run_command(cmd, timeout=180, capture=False)

    if returncode == 0:
        result.success = True
        result.output = stdout or "Flashing completed successfully."
        print("-" * 70)
        print("Flash successful.")
    else:
        result.error = stderr or stdout or f"esptool exited with code {returncode}"
        print("-" * 70)
        print(f"Flash failed: {result.error}", file=sys.stderr)

    return result


def erase_flash(port: str, chip: str = "") -> FlashResult:
    """Erase the entire flash of an ESP32 device."""
    result = FlashResult(success=False)
    esptool = find_esptool()
    if not esptool:
        result.error = "esptool.py not found."
        return result

    if not chip:
        devices = detect_devices(identify=True)
        device = select_port(devices, port)
        if device and device.chip_model:
            chip = device.chip_model
            port = device.port
        else:
            chip = "esp32"  # fallback

    cmd = esptool.split() + ["--chip", chip, "--port", port, "erase_flash"]
    result.command = " ".join(cmd)
    result.port = port
    result.chip = chip

    print(f"Erasing flash on {chip} at {port}...")
    returncode, stdout, stderr = run_command(cmd, timeout=120, capture=False)

    if returncode == 0:
        result.success = True
        result.output = "Flash erased successfully."
    else:
        result.error = stderr or stdout or "Erase failed."

    return result


def main():
    parser = argparse.ArgumentParser(description="Flash ESP32 firmware with auto-detection")
    parser.add_argument("project_dir", nargs="?", default=".", help="Project directory (default: current)")
    parser.add_argument("--port", "-p", default="", help="Serial port (e.g. COM6, /dev/ttyUSB0). Auto-detected if omitted.")
    parser.add_argument("--chip", "-c", default="", help="Chip model: esp32, esp32s2, esp32s3, esp32c3, esp32c6, esp32h2")
    parser.add_argument("--baud", "-b", type=int, default=460800, help="Baud rate (default: 460800)")
    parser.add_argument("--erase", action="store_true", help="Erase entire flash before flashing")
    parser.add_argument("--no-verify", action="store_true", help="Skip flash verification")
    parser.add_argument("--dry-run", action="store_true", help="Print command without executing")
    parser.add_argument("--no-identify", action="store_true", help="Skip esptool chip_id (faster)")
    parser.add_argument("--bin", help="Explicit path to a .bin file to flash at --offset")
    parser.add_argument("--offset", default="0x10000", help="Offset for explicit --bin (default: 0x10000)")
    parser.add_argument("--json", action="store_true", help="Output result as JSON")
    args = parser.parse_args()

    root = Path(args.project_dir)

    if args.erase and not args.project_dir == "." and not args.bin:
        # Pure erase mode
        result = erase_flash(port=args.port, chip=args.chip)
    elif args.bin:
        # Flash a single explicit binary
        result = FlashResult(success=False)
        esptool = find_esptool()
        if not esptool:
            result.error = "esptool.py not found."
        else:
            bin_path = Path(args.bin)
            if not bin_path.exists():
                result.error = f"Binary not found: {bin_path}"
            else:
                devices = detect_devices(identify=not args.no_identify)
                device = select_port(devices, args.port)
                if not device:
                    result.error = "No serial port found."
                else:
                    chip = args.chip or device.chip_model or "esp32"
                    img = FlashImage(offset=args.offset, path=bin_path, role="custom")
                    cmd = build_flash_command(esptool, chip, device.port, args.baud, [img], verify=not args.no_verify)
                    result.command = " ".join(cmd)
                    result.port = device.port
                    result.chip = chip
                    result.images = [img]
                    if not args.dry_run:
                        rc, out, err = run_command(cmd, timeout=180, capture=False)
                        result.success = (rc == 0)
                        result.output = out
                        result.error = err
                    else:
                        result.success = True
    else:
        result = flash_project(
            root=root,
            port=args.port,
            baud=args.baud,
            chip=args.chip,
            erase=args.erase,
            verify=not args.no_verify,
            dry_run=args.dry_run,
            no_identify=args.no_identify,
        )

    if args.json:
        output = {
            "success": result.success,
            "port": result.port,
            "chip": result.chip,
            "command": result.command,
            "images": [{"offset": i.offset, "path": str(i.path), "role": i.role} for i in result.images],
            "error": result.error,
        }
        print(json.dumps(output, indent=2, ensure_ascii=False))

    sys.exit(0 if result.success else 1)


if __name__ == "__main__":
    main()
